Implement basic navigation with Compose Destinations
openworld-community/Datify-Android-Core pull request #1
Opened 2023-09-07 23:04 UTC by madrazzl3

Ticket AND-32

2023-09-07 23:07 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/ui/composables/BottomBar.kt
> +//enum class BottomBarScreenItem(
По какой-то причине мой локальный билд спотыкается на шаге с ksp на этом коде
Надо будет разобраться, в чём проблема

2023-09-08 10:45 UTC, madrazzl3 commented on app/build.gradle.kts
> +    implementation(libs.compose.destinations)
Пока заюзал библиотеку [Compose Destinations](https://composedestinations.rafaelcosta.xyz), выглядит достаточно понятно. Основная проблема - нестабильный ksp плагин, который крашится без нормального сообщения об ошибках, дебажить это вообще не понравилось.

[Appyx](https://bumble-tech.github.io/appyx/) выглядит достаточно круто, кажется там можно написать более понятную и структурированную навигацию (но порог входа кажется выше)

Так же можно рассмотреть [Voyager](https://voyager.adriel.cafe), я не работал с ним, но API довольно понятное

Пока предлагаю взять эту реализацию за дефолтную, и в отдельной ветке сделать эксперимент с Appyx, и если всем в команде будет понятно, как с ним работать, вольём в main

2023-09-08 14:33 UTC, berhram requested changes

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/chats/ChatsScreen.kt
> +    Row(modifier = Modifier.fillMaxSize().fillMaxHeight(),
fillMaxSize уже содержит в себе fillMaxHeight & fillMaxWidth, можно убрать

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/data/LoginStateRepository.kt
> +    override suspend fun login() = withContext(Dispatchers.IO) {
мб просто _isLoggedIn.value = true вместо  другого контексте

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/login/LoginScreen.kt
> +    Row(modifier = Modifier.fillMaxWidth().fillMaxHeight(),
заменить на fillMaxSize

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +    Row(modifier = Modifier.fillMaxSize().fillMaxHeight(),
fillMaxSize

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/menu/MenuScreen.kt
> +    Row(modifier = Modifier.fillMaxSize().fillMaxHeight(),
remove fillMaxHeight

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/menu/MenuScreen.kt
> +    viewModel: MenuViewModel = hiltViewModel()
хз стоит ли в параметрах тогда держать раз здесь же и запрашиваем, мб в тело функции перенести?

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/ui/DatifyAppContent.kt
> +                modifier = Modifier
лучше поменять порядок модифаеров, интуитивнее читаться будет

2023-09-08 14:33 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/ui/composables/TopBar.kt
> +    TopAppBar(title = @Composable { Text(text = destination.topBarTitle() )})
тут аннотация не нужна вроде как

2023-09-08 14:35 UTC, berhram commented on app/build.gradle.kts
> +    implementation(libs.compose.destinations)
мне нравится Destinations тем что там стоковый Jetp. Nav. под капотом и поэтому перформанс хороший будет, я бы его и оставил

2023-09-08 14:43 UTC, berhram commented on app/src/main/java/com/datify/datifyapp/menu/MenuScreen.kt
> +    viewModel: MenuViewModel = hiltViewModel()
Хотя в примерах везде в аргументах, надо посмотреть что будет

2023-09-08 15:04 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/data/LoginStateRepository.kt
> +    override suspend fun login() = withContext(Dispatchers.IO) {
Это просто копипаста из тестового проекта библиотеки навигации, это всё перепишется

2023-09-08 15:06 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/menu/MenuScreen.kt
> +        Button(onClick = viewModel::logout) {
Ого, спасибо за информацию!

2023-09-11 10:11 UTC, merged