Password creation screen
openworld-community/Datify-Android-Core pull request #18
Opened 2023-11-13 01:16 UTC by Zizap

Сверстал экран создания пароля: https://apridexxi.atlassian.net/browse/AND-44?atlOrigin=eyJpIjoiMzBiNTE4NzdmZmI0NDU0YTkyYWYyNzYxMzEwMjQzNDMiLCJwIjoiaiJ9

2023-11-16 20:43 UTC, madrazzl3 requested changes

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/res/values/strings.xml
> +    <string name="the_password_must_contain_at_least_8_characters_and_should_not_be_used_anywhere_else">The password must contain at least 8 characters and should not be used anywhere else</string>
`the_password_must_contain_at_least_8_characters_and_should_not_be_used_anywhere_else`

Перестарался :D

Пусть будет `password_requirements`

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/res/values/strings.xml
> +    <string name="choose_a_password_for_the_account">Create a password</string>
На будущее -- думаю можно в названиях строк опускать артикли, в угоду краткости

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun passwordValidation(password: String): Boolean {
Из названия я решил, что `passwordValidation` выдаёт true, если пароль правильный. Нужно отразить в названии (что-то типа "isPasswordIncorrect"), но обычно всё-таки принято делать функции без отрицания (т.е. переименовать её в `validatePassword` / `isPasswordValid`, и возвращать true для правильного пароля, и  поменять тут на `insertionError = ! isPasswordValid()`

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    fun mirrorPassword(password: String, repeatPassword: String = "") {
1. Мне не очень нравится название, мне не очевидно, что это значит в этом контексте. Было бы лучше `setPasswordConfirmation` / `setPasswordRepetition`
2. Зачем передавать оригинальный password? Ты можешь его брать прямо из стейта, там где ты делаешь 

```kotlin
_passwordCreationUiState.update { previousState ->
// тут previousState содержит старое состояние, ты можешь вытащить пароль отсюда
}
```

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +        Row(
У нас из экрана в экран повторяется содержимое этих Preview, можем вынести куда-нибудь

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                    if ((passwordCreationUiState.password?: "").length in 8..32) {
Вся логика должна быть во ViewModel, но ты можешь передавать в UI enum или sealed object/class/interface

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
А символы вводятся как точки/звёздочки?

2023-11-16 20:43 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
И ещё надо добавить кнопку "глазик" для показа/прятания пароля

2023-11-17 02:46 UTC, Zizap commented on app/src/main/res/values/strings.xml
> +    <string name="the_password_must_contain_at_least_8_characters_and_should_not_be_used_anywhere_else">The password must contain at least 8 characters and should not be used anywhere else</string>
ахаха, просто я сам их не пишу, они же генерятся

2023-11-17 02:46 UTC, Zizap commented on app/src/main/res/values/strings.xml
> +    <string name="the_password_must_contain_at_least_8_characters_and_should_not_be_used_anywhere_else">The password must contain at least 8 characters and should not be used anywhere else</string>
fix

2023-11-17 02:47 UTC, Zizap commented on app/src/main/res/values/strings.xml
> +    <string name="choose_a_password_for_the_account">Create a password</string>
лады

2023-11-17 02:50 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun passwordValidation(password: String): Boolean {
fix

2023-11-17 03:30 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    fun mirrorPassword(password: String, repeatPassword: String = "") {
fix

2023-11-17 03:36 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +        Row(
fix

2023-11-17 03:50 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
В жире была прикреплена документация: https://www.ibm.com/docs/en/baw/20.x?topic=security-characters-that-are-valid-user-ids-passwords
В ней сказано вот что:
Поддерживаемые символы:

Строчные буквы {a-z}
Прописные буквы {A-Z}
Цифры {0-9}
Восклицательный знак {!}
Открывающая скобка {(}
Закрывающая скобка {)}
Знак вопроса {?}
Открывающая квадратная скобка {[}
Закрывающая квадратная скобка {]}
Подчеркивание {_}
Обратная кавычка {`}
Тильда {~}
Собачий знак {@}
Знак номера {#}
Знак доллара {$}
Циркумфлекс {^}
Амперсанд {&}
Звездочка {*}
Плюс {+}
Знак равенства {=}
Примечание: Дефис (-) и точка (.) не поддерживаются в качестве первого символа в идентификаторе пользователя или пароле.

2023-11-17 03:50 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
В макете нет глазика 
![image](https://github.com/openworld-community/Datify-Android-Core/assets/57288682/9acf75b8-00c3-4e72-890e-60d1a9addc33)

2023-11-17 05:08 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                    if ((passwordCreationUiState.password?: "").length in 8..32) {
fix 
![image](https://github.com/openworld-community/Datify-Android-Core/assets/57288682/1ebdbc14-8c70-4f63-b9e6-31f7aa49c547)

2023-11-17 14:45 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                    if ((passwordCreationUiState.password?: "").length in 8..32) {
Вместо null можно поставить `Unit` или `{ }`

2023-11-17 14:46 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
> В жире была прикреплена документация: https://www.ibm.com/docs/en/baw/20.x?topic=security-characters-that-are-valid-user-ids-passwords В ней сказано вот что: Поддерживаемые символы:
> 
> Строчные буквы {a-z} Прописные буквы {A-Z} Цифры {0-9} Восклицательный знак {!} Открывающая скобка {(} Закрывающая скобка {)} Знак вопроса {?} Открывающая квадратная скобка {[} Закрывающая квадратная скобка {]} Подчеркивание {_} Обратная кавычка {`} Тильда {~} Собачий знак {@} Знак номера {#} Знак доллара {$} Циркумфлекс {^} Амперсанд {&} Звездочка {*} Плюс {+} Знак равенства {=} Примечание: Дефис (-) и точка (.) не поддерживаются в качестве первого символа в идентификаторе пользователя или пароле.

Я имел ввиду скрытие символов, но ладно, пока оставим так

2023-11-17 14:54 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationScreen.kt
> +                    if ((passwordCreationUiState.password?: "").length in 8..32) {
натуре, исправил

2023-11-17 15:06 UTC, madrazzl3 requested changes

2023-11-17 15:06 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            password[0] == '.' || password[0] != '-' -> PasswordErrorState.Incorrect
Странно проверять это условие дважды, потом надо в двух местах его изменять, если понадобится.
Ты можешь поставить его до строки `(password.length in 8..32) && (password[0] != '.') ...`, тогда там его можно будет опустить

2023-11-17 15:06 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun isPasswordValid(password: String): PasswordErrorState  {
Название `isPasswordValid` подразумевает, что функция возвращает true/false, стоит переименовать

2023-11-17 15:06 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +        val newState = PasswordCreationUiState (
Т.е. если я написал пароль, потом написал его подтверждение, а потом дописал одну букву в пароль, то подтверждение сотрётся?

2023-11-17 15:10 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +        val newState = PasswordCreationUiState (
да

2023-11-17 15:44 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            password[0] == '.' || password[0] != '-' -> PasswordErrorState.Incorrect
fix

2023-11-17 15:44 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +                insertionError = isPasswordValid(previousState.password ?: ""),
fix

2023-11-17 15:44 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +                    when (isPasswordValid(previousState.password ?: "")) {
fix

2023-11-17 15:44 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun isPasswordValid(password: String): PasswordErrorState  {
fix

2023-11-17 16:02 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +//код на случай если нам понадобится проверять сложность пароля
пока уберу

2023-11-18 12:38 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +        val newState = PasswordCreationUiState (
Так точно не стоит делать, давай исправим это поведение. Ты можешь использовать функцию .copy если нужно

2023-11-18 12:48 UTC, madrazzl3 requested changes
Давай исправим поведение со стирающимся подтверждением пароля. Всё остальное сделано хорошо и можно заливать.

2023-11-18 12:48 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/customui/ErrorTextForTextField.kt
> +    if (insertionError) {
Я всё же не очень понимаю, зачем нам этот if внутри компонента, почему мы не делаем if там где используем эти ErrorText

2023-11-18 12:48 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            (password.length in 8..32) && (password == filteredValue) -> PasswordErrorState.Valid
По-идее это условие лишнее, у тебя его обработает else

2023-11-18 12:49 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun checkingErrorStatus(password: String): PasswordErrorState  {
Лучше назвать `validatePassword`

2023-11-18 13:23 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/customui/ErrorTextForTextField.kt
> +    if (insertionError) {
убрал

2023-11-18 13:25 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            (password.length in 8..32) && (password == filteredValue) -> PasswordErrorState.Valid
fix

2023-11-18 15:08 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +    private fun checkingErrorStatus(password: String): PasswordErrorState  {
fix

2023-11-18 15:58 UTC, madrazzl3 approved these changes
Есть что поправить, но в целом хорошо

2023-11-18 15:58 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/customui/ErrorTextForTextField.kt
> +fun ErrorText(text:Int) {
Можно пометить аргумент аннотацией `@StringRes`

2023-11-18 15:58 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            (password.isNotEmpty()) && ((password[0] == '.') || (password[0] == '-')) -> PasswordErrorState.Incorrect
isEmpty тоже можно поставить на первое место и избавиться от `password.isNotEmpty()`

2023-11-18 15:58 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +                PasswordCreationUiState(
Вроде как повторение с блоком на строке 55, можно как-то объединить думаю

2023-11-18 16:06 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/customui/ErrorTextForTextField.kt
> +fun ErrorText(text:Int) {
fix

2023-11-18 16:08 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +            (password.isNotEmpty()) && ((password[0] == '.') || (password[0] == '-')) -> PasswordErrorState.Incorrect
fix

2023-11-18 16:12 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/password/PasswordCreationViewModel.kt
> +                PasswordCreationUiState(
Мне кажется не получится, так как 1 функция работает в 1 TextField, а 2 во втором. И нужно чтобы они записывались в PasswordCreationUiState отдельно.

2023-11-18 23:15 UTC, madrazzl3 approved these changes

2023-11-18 23:15 UTC, merged