Main screen
openworld-community/Datify-Android-Core pull request #26
Opened 2023-12-09 09:47 UTC by Zizap

Сверстал главный экран.

2023-12-09 13:07 UTC, madrazzl3 requested changes

2023-12-09 13:07 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                                    text = user.description,
(Если я правильно понял проблему, то тут надо не width задавать, а weight у столбца)

2023-12-09 13:07 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                        var visible by remember {
Потом вынесем в UiState во ViewModel

2023-12-09 13:07 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                            text = "${user.name},${user.age}",
Через пробел

2023-12-09 13:08 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/gender/GendersModel.kt
> +enum class GendersModel(@StringRes val label: Int) {
Лучше назови `Gender`

2023-12-09 17:30 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/gender/GendersModel.kt
> +enum class GendersModel(@StringRes val label: Int) {
Лады

2023-12-09 17:30 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/login/LoginScreen.kt
> +            viewModel.login()
лады

2023-12-09 17:31 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/theme/Theme.kt
> +            window.statusBarColor = Color.Transparent.toArgb()
Да, иначе как сделать я не нашел

2023-12-09 17:38 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/composables/TopBar.kt
> +                    .statusBarsPadding(),
убрал .padding(vertical = 12.dp)

2023-12-09 17:39 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/composables/TopBar.kt
> +                Box {
![image](https://github.com/openworld-community/Datify-Android-Core/assets/57288682/81b09d46-f8a9-4f15-9b30-4d4a0f7e9cbd)

2023-12-09 17:45 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        val shadowGradient = Brush.verticalGradient(
Вынес

2023-12-09 18:04 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                                    text = user.description,
fix

2023-12-09 18:07 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        Box {
натуре, это похоже пережиток прошлого

2023-12-09 18:08 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        Box {
Так называемый рудимент

2023-12-09 18:08 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                        var visible by remember {
лады

2023-12-09 18:09 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                            text = "${user.name},${user.age}",
fix

2023-12-12 16:57 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/MainActivity.kt
> +            statusBarStyle = SystemBarStyle.light(
fix

2023-12-12 16:58 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/StatusesModel.kt
> +enum class StatusesModel (
fix

2023-12-13 18:56 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                            contentDescription = "",
fix

2023-12-13 18:56 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                            contentDescription = "",
fix

2023-12-14 12:02 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                Icon(
fix

2023-12-14 12:05 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                        onClick = { /*TODO*/ }
есть

2023-12-14 12:05 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +        title = {
fix

2023-12-14 12:09 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +            contentDescription = "",
есть

2023-12-14 12:10 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +fun PagerCount(pagerState: PagerState) {
fix

2023-12-14 12:20 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +            val color = if (pagerState.currentPage == iteration) Color(1f, 1f, 1f) else Color(1f, 1f, 1f, 0.32f)
есть

2023-12-14 12:22 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +fun MainScreenContent(
Оставил FeedScreen

2023-12-14 12:46 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/DatifyAppContent.kt
> +                    .padding(bottom = innerPadding.calculateBottomPadding()),
https://youtu.be/pLMw9Vlbfgw вот тут это решение подсматрел

2023-12-15 09:50 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                Row(
Я тут коменты оставлял, но они чота удалились. Вообщем я теперь использую actions и title

2023-12-15 14:08 UTC, madrazzl3 requested changes

2023-12-15 14:08 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                            contentDescription = "",
Смотри, мы заполняем contentDescription для функциональных элементов (кнопки, слайдеры), и не заполняем для декоративных (логотипы, градиенты, тени)
Надо заполнить тут

2023-12-15 14:08 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +    VerticalPager(
У VerticalPager есть параметр key, имеет смысл задавать его, это должно уменьшить количество лишних рекомпозиций

2023-12-16 08:35 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/username/UserNameInputScreen.kt
> +                .weight(0.7f,true),
[экранчики.zip](https://github.com/openworld-community/Datify-Android-Core/files/13691877/default.zip)
Во посмари

2023-12-16 08:36 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/UserCardModel.kt
> +    val visibleDescription: Boolean = false
fix

2023-12-16 08:39 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +    Box {
Не нужен, убрал

2023-12-16 08:41 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +                        contentDescription = "setting_button",
fix

2023-12-16 08:41 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/MainTopBar.kt
> +    notificationButton: () -> Unit
fix

2023-12-16 08:43 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/sms/VerifySMSCodeScreen.kt
>          Column(
Ой, случайно, убрал

2023-12-16 09:34 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedViewModel.kt
> +            val updatedList = previousState.list.map { userCardModel ->
Заменил List на Map. Памяти теперь расходуется, примерно, на 20% меньше, но лаги остались, походу дело не в этом

2023-12-16 09:39 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                        if (it) {
назвал isScrolling

2023-12-16 10:22 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                    snapshotFlow { pagerState.isScrollInProgress }.collect {
Сколько раз вызывается это событие при скролле?
closeDescription 1 раз.
Сделал, вроде немного помогло

2023-12-16 10:27 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                else Modifier
неа, попробывал твой вариант, не работает

2023-12-16 10:29 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                            contentDescription = "",
fix

2023-12-16 10:33 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +    VerticalPager(
Сделано

2023-12-17 12:35 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                else Modifier
Окей, не apply, а run например

```
Modifier.fillMaxSize()
.run {
    if (user.visibleDescription) this.blur() else this
}
```

2023-12-18 13:05 UTC, madrazzl3 approved these changes

2023-12-18 13:05 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedViewModel.kt
> +            val updatedUser = previousState.userMap[id]?.copy(like = !(previousState.userMap[id]!!.like)) ?: return@update previousState
Можно убрать !! и просто ввести промежуточную переменную для пользователя

2023-12-18 13:05 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        key = { index -> uiState.userMap[index]?.id ?: index }
А точно стоит возвращать index если не нашли id? Что пишут в документации?

2023-12-18 14:04 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                    snapshotFlow { pagerState.isScrollInProgress }.collect {
closeDescription вызывается 1 раз. 
сделал как там

2023-12-18 14:13 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +                else Modifier
apply не работает сделал так 
modifier = Modifier.fillMaxSize()
                    .run {
                        if (user.isDescriptionVisible) Modifier.blur(radius = 8.dp) else Modifier
                    },

2023-12-18 14:29 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        key = { index -> uiState.userMap[index]?.id ?: index }
Исправлю это во время написании пагинации, так еще не придумал, как будет обновляться map с новыми пользователями

2023-12-18 14:34 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        key = { index -> uiState.userMap[index]?.id ?: index }
Возвращать index стоит только в том случае, если у нас будут уникальные id у всех пользователей. Тогда с эти проблем не будет. И еще как мы будем хранить все карточки пользователей, в случаи когда юзер листает их очень много и захочет вернуться на 100 карточек назад. Нужно получается хранить все, что он проскролил

2023-12-18 14:38 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/meetings/FeedViewModel.kt
> +            val updatedUser = previousState.userMap[id]?.copy(like = !(previousState.userMap[id]!!.like)) ?: return@update previousState
есть

2023-12-18 14:39 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/meetings/FeedScreen.kt
> +        key = { index -> uiState.userMap[index]?.id ?: index }
> Возвращать index стоит только в том случае, если у нас будут уникальные id у всех пользователей

будет уникальный индекс у каждого пользователя, да

> Нужно получается хранить все, что он проскролил

Да, ну с этим особых проблем не будет. Сколько одна карточка может занимать? 1 кб? Ну даже если их будет 1000, это 1 мб, меньше чем весит одна фотка из любого профиля

2023-12-19 12:44 UTC, madrazzl3 commented on app/src/main/java/com/datify/datifyapp/ui/composables/TopBar.kt
> +            MenuScreenDestination -> MeetingsTopBar(
Не обратил внимание, но Даня подсказал, что тут есть проблема с тем, чтобы прокидывать onSettingClick и onNotificationsClick из FeedScreenViewModel. Возможно стоит перенести этот тулбар в FeedScreen

2023-12-20 09:54 UTC, merged

2023-12-20 09:55 UTC, Zizap commented on app/src/main/java/com/datify/datifyapp/ui/composables/TopBar.kt
> +            MenuScreenDestination -> MeetingsTopBar(
перенесу в следующем пре